# Generated by Django 4.1 on 2026-05-29 06:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shelter", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pet",
            options={"ordering": ["id"]},
        ),
        migrations.DeleteModel(
            name="Volunteer",
        ),
    ]
